// integrations/vue/Comment.vue
<script setup>
// StaticLayer — Vue component (works in Vue 3 / Nuxt).
// Usage: <Comments endpoint="https://comments.example.com" reactions="👍,❤️,🎉" />
defineProps({
  endpoint: { type: String, required: true },
  articlePath: { type: String, default: '' },
  reactions: { type: String, default: '' },
  pollId: { type: String, default: '' },
  pollStyle: { type: String, default: '' },
  pollResults: { type: String, default: '' },
  sort: { type: String, default: '' },
  reactionsPosition: { type: String, default: '' },
  lang: { type: String, default: '' },
  theme: { type: String, default: '' },
  accent: { type: String, default: '' },
  accent2: { type: String, default: '' },
  radius: { type: String, default: '' },
  maxWidth: { type: String, default: '' },
});

function attrs(p) {
  const a = { 'data-staticlayer': '', 'data-endpoint': p.endpoint };
  if (p.articlePath) a['data-article-path'] = p.articlePath;
  if (p.reactions) a['data-reactions'] = p.reactions;
  if (p.pollId) a['data-poll-id'] = p.pollId;
  if (p.pollStyle) a['data-poll-style'] = p.pollStyle;
  if (p.pollResults) a['data-poll-results'] = p.pollResults;
  if (p.sort) a['data-comments-sort'] = p.sort;
  if (p.reactionsPosition) a['data-reactions-position'] = p.reactionsPosition;
  if (p.lang && p.lang !== 'auto') a['data-lang'] = p.lang;
  if (p.theme && p.theme !== 'auto') a['data-theme'] = p.theme;
  if (p.accent) a['data-accent'] = p.accent;
  if (p.accent2) a['data-accent-2'] = p.accent2;
  if (p.radius) a['data-radius'] = p.radius;
  if (p.maxWidth) a['data-max-width'] = p.maxWidth;
  return a;
}
</script>

<template>
  <div>
    <div v-bind="attrs($props)"></div>
    <script :src="endpoint + '/widget.js'" defer />
  </div>
</template>

// integrations/react/Comment.tsx
// StaticLayer — React component (works in Next.js, Vite, Astro islands…).
// Usage:
//   <Comments endpoint="https://comments.example.com" reactions="👍,❤️,🎉" sort="best" />
type CommentsProps = {
  endpoint: string;
  articlePath?: string;
  reactions?: string;
  reactionsOnly?: boolean;
  pollId?: string;
  pollStyle?: 'bars' | 'percent' | 'counts' | 'minimal';
  pollResults?: 'after' | 'always';
  sort?: 'newest' | 'oldest' | 'best';
  reactionsPosition?: 'top' | 'bottom';
  lang?: 'en' | 'it' | 'auto';
  theme?: 'auto' | 'light' | 'dark';
  accent?: string;
  accent2?: string;
  radius?: string;
  maxWidth?: string;
};

export function Comments(props: CommentsProps) {
  const { endpoint, reactionsOnly, pollId, ...rest } = props;
  const attrs: Record<string, string> = {
    'data-staticlayer': '',
    'data-endpoint': endpoint,
  };
  if (rest.articlePath) attrs['data-article-path'] = rest.articlePath;
  if (rest.reactions) attrs['data-reactions'] = rest.reactions;
  if (reactionsOnly) attrs['data-reactions-only'] = '';
  if (reactionsOnly && rest.reactionsPosition) attrs['data-reactions-position'] = rest.reactionsPosition;
  if (pollId) {
    attrs['data-poll-id'] = pollId;
    if (rest.pollStyle) attrs['data-poll-style'] = rest.pollStyle;
    if (rest.pollResults) attrs['data-poll-results'] = rest.pollResults;
  }
  if (rest.sort) attrs['data-comments-sort'] = rest.sort;
  if (rest.lang && rest.lang !== 'auto') attrs['data-lang'] = rest.lang;
  if (rest.theme && rest.theme !== 'auto') attrs['data-theme'] = rest.theme;
  if (rest.accent) attrs['data-accent'] = rest.accent;
  if (rest.accent2) attrs['data-accent-2'] = rest.accent2;
  if (rest.radius) attrs['data-radius'] = rest.radius;
  if (rest.maxWidth) attrs['data-max-width'] = rest.maxWidth;

  return (
    <>
      <div {...attrs} />
      <script src={`${endpoint}/widget.js`} defer />
    </>
  );
}
